# Matrix Inversion

The inverse of a matrix $A$ is a matrix $A^{-1}$ such that $A \cdot A^{-1} = A^{-1} \cdot A = I$, where $I$ is the identity matrix.

**Example 1:**

In [ ]:
import sympy as sp # import sympy library
k1 = sp.Matrix([[2, 1, 2], [5, 3, 1], [1, 1, 5]]) # create matrix k1
k1

Matrix([
[2, 1, 2],
[5, 3, 1],
[1, 1, 5]])

In [ ]:
inverse_k1 = k1.inv() # calculate the inverse of matrix k1
inverse_k1

Matrix([
[7/4, -3/8, -5/8],
[ -3,    1,    1],
[1/4, -1/8,  1/8]])

In [ ]:
k1 * inverse_k1 # verify if multiplying the matrix by its inverse yields the identity matrix

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

**Example 2:**

In [ ]:
import sympy as sp
a, b, c, d, e, f, g, h, i = sp.symbols('a b c d e f g h i') # define variables a-i
k = sp.Matrix([[a, b, c], [d, e, f], [g, h, i]]) # create matrix k
inverse_k = k.inv()
inverse_k

Matrix([
[ (e*i - f*h)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g), (-b*i + c*h)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g),  (b*f - c*e)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g)],
[(-d*i + f*g)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g),  (a*i - c*g)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g), (-a*f + c*d)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g)],
[ (d*h - e*g)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g), (-a*h + b*g)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g),  (a*e - b*d)/(a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g)]])

This complex form results from the formula that allows for the calculation of the elements of the inverse matrix. Before we proceed, let's define a few concepts.

**Matrix Transposition** is an operation that swaps rows with columns. The transpose of a matrix $A$ is a matrix $A^T$ such that $A^T_{ij} = A_{ji}$.

In [ ]:
k

Matrix([
[a, b, c],
[d, e, f],
[g, h, i]])

In [ ]:
k.transpose() # transpose matrix k

Matrix([
[a, d, g],
[b, e, h],
[c, f, i]])

**Minor** of a matrix $A$ is the determinant of the matrix obtained by removing the $i$-th row and $j$-th column. We denote it by $M_{ij}$.

In [ ]:
# Minor of matrix $A$ is the determinant of the matrix obtained by removing the $i$-th row and $j$-th column. We denote it by $M_{ij}$.
k2 = sp.Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k2

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [ ]:
M01 = k2.minor_submatrix(0, 1) # calculate minor M01
M01

Matrix([
[4, 6],
[7, 9]])

In [ ]:
M22 = k2.minor_submatrix(2, 2) # calculate minor M22
M22

Matrix([
[1, 2],
[4, 5]])

**Cofactor** of element $a_{ij} = (-1)^{i+j} \, M_{ij}$, which is the minor multiplied by $(-1)^{i+j}$.

**Rank of a Matrix** is the largest degree of a non-zero minor of the matrix. The rank of a matrix is equal to the number of linearly independent rows or columns in the matrix.

In [ ]:
k2.rank() # calculate the rank of matrix k2

2

### Inverse of a 3x3 Matrix

Using the transpose of the cofactor matrix (minors):

$$K^{-1} =
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}^{-1}
= \frac{1}{\det(\mathbf{K})}
\begin{bmatrix}
A & B & C \\
D & E & F \\
G & H & I
\end{bmatrix}^T
= \frac{1}{\det(\mathbf{A})}
\begin{bmatrix}
A & D & G \\
B & E & H \\
C & F & I
\end{bmatrix}
$$

If the determinant is non-zero, the matrix is invertible, and the elements of the intermediate matrix on the right-hand side of the above formula are determined by:

$$
\begin{aligned}
A &= \text{det} \left( \begin{bmatrix} e & f \\ h & i \end{bmatrix} \right) & B &= -\text{det} \left( \begin{bmatrix} d & f \\ g & i \end{bmatrix} \right) & C &= \text{det} \left( \begin{bmatrix} d & e \\ g & h \end{bmatrix} \right) \\
D &= -\text{det} \left( \begin{bmatrix} b & c \\ h & i \end{bmatrix} \right) & E &= \text{det} \left( \begin{bmatrix} a & c \\ g & i \end{bmatrix} \right) & F &= -\text{det} \left( \begin{bmatrix} a & b \\ g & h \end{bmatrix} \right) \\
G &= \text{det} \left( \begin{bmatrix} b & c \\ e & f \end{bmatrix} \right) & H &= -\text{det} \left( \begin{bmatrix} a & c \\ d & f \end{bmatrix} \right) & I &= \text{det} \left( \begin{bmatrix} a & b \\ d & e \end{bmatrix} \right)
\end{aligned}
$$

These are the determinants of 2x2 matrices formed by removing the appropriate rows and columns and taking into account the sign $(-1)^{i+j}$.

### Inverse of a 2x2 Matrix

Similarly, for a 2x2 matrix, the inverse can be calculated using the cofactor matrix:

$$
\mathbf{L}^{-1} =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}^{-1}
= \frac{1}{\det(\mathbf{L})}
\begin{bmatrix}
D & C \\
B & A
\end{bmatrix}^T
= \frac{1}{\det(\mathbf{L})}
\begin{bmatrix}
D & B \\
C & A
\end{bmatrix}
$$

where $\det(\mathbf{L}) = ad - bc$

If the determinant is non-zero, the matrix is invertible, and the elements of the intermediate matrix are given as:

$$
\begin{aligned}
A &= \text{det} \begin{bmatrix} d \end{bmatrix} = d, & B &= -\text{det} \begin{bmatrix} b \end{bmatrix} = -b, & C &= -\text{det} \begin{bmatrix} c \end{bmatrix} = -c, &
D &= \text{det} \begin{bmatrix} a \end{bmatrix} = a.
\end{aligned}
$$

These elements are determined by calculating the determinants of 1x1 matrices formed by removing the appropriate rows and columns from the original 2x2 matrix and applying the corresponding signs $(-1)^{i+j}$.

---

## Exercises for Students

1. Find the inverse matrix for

$$
\begin{bmatrix}
2 & 0 & 1 \\
0 & 1 & 0 \\
1 & 2 & 0
\end{bmatrix}
$$

and verify if the result is correct.

2. Using the `det()` command, determine the rank of the matrix below
$$
A =
\begin{bmatrix}
4 & -3 & 7 \\
-1 & 6 & 3 \\
2 & 9 & 1
\end{bmatrix}
$$

In [ ]:
#first of all we calculate d if d doesnt equal 0 it is invertable

In [1]:
import numpy as np

# Define matrix K
K = np.array([
    [2, 0, 1],
    [0, 1, 2],
    [1, 0, 0]
], dtype=float)

# Step 1: Calculate the determinant of K
det_K = np.linalg.det(K)
print(f"Determinant of K: {det_K}")

# Step 2: Calculate the cofactor matrix manually
cofactor_matrix = np.array([
    [np.linalg.det(np.array([[1, 2], [0, 0]])),    -np.linalg.det(np.array([[0, 2], [1, 0]])),    np.linalg.det(np.array([[0, 1], [1, 0]]))],
    [-np.linalg.det(np.array([[0, 1], [0, 0]])),    np.linalg.det(np.array([[2, 1], [1, 0]])),    -np.linalg.det(np.array([[2, 0], [1, 1]]))],
    [np.linalg.det(np.array([[0, 1], [1, 2]])),     -np.linalg.det(np.array([[2, 1], [1, 0]])),    np.linalg.det(np.array([[2, 0], [0, 1]]))]
])

# Print the cofactor matrix
print("Cofactor Matrix:")
print(cofactor_matrix)

# Step 3: Transpose the cofactor matrix to get the adjugate
adjugate_matrix = cofactor_matrix.T

# Print the adjugate matrix
print("Adjugate Matrix:")
print(adjugate_matrix)

# Step 4: Divide the adjugate by the determinant to get the inverse
K_inverse = adjugate_matrix / det_K

# Print the inverse
print("Inverse of K:")
print(K_inverse)

Determinant of K: -1.0
Cofactor Matrix:
[[ 0.  2. -1.]
 [-0. -1. -2.]
 [-1.  1.  2.]]
Adjugate Matrix:
[[ 0. -0. -1.]
 [ 2. -1.  1.]
 [-1. -2.  2.]]
Inverse of K:
[[-0.  0.  1.]
 [-2.  1. -1.]
 [ 1.  2. -2.]]


In [2]:
import numpy as np

# Define the matrix A
A = np.array([
    [4, -1, 2],
    [-3, 6, -9],
    [7, 3, 1]
])

# Calculate the determinant of A
determinant = np.linalg.det(A)

# Print the determinant and the rank
print("Determinant of matrix A:", determinant)

# Determine the rank based on the determinant
if determinant != 0:
    print("The rank of matrix A is 3 because the determinant is not zero.")
else:
    print("The rank of matrix A is less than 3 because the determinant is zero.")


Determinant of matrix A: 90.0
The rank of matrix A is 3 because the determinant is not zero.
